// scripts/setup.js
// Interactive setup wizard. Guides a new user from zero to running.
// Usage: node scripts/setup.js

import { createInterface }  from 'readline'
import { writeFileSync, readFileSync, existsSync } from 'fs'
import { execSync }         from 'child_process'
import path                 from 'path'
import { fileURLToPath }    from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT      = path.join(__dirname, '..')
const API_DIR   = path.join(ROOT, 'api')
const ENV_PATH  = path.join(API_DIR, '.env')

const rl = createInterface({ input: process.stdin, output: process.stdout })
const ask = (q) => new Promise(r => rl.question(q, r))
const askSecret = (q) => new Promise(r => {
  process.stdout.write(q)
  process.stdin.setRawMode?.(true)
  let val = ''
  const handler = (buf) => {
    const ch = buf.toString()
    if (ch === '\r' || ch === '\n') {
      process.stdin.setRawMode?.(false)
      process.stdin.removeListener('data', handler)
      process.stdout.write('\n')
      r(val)
    } else if (ch === '\u007f') {
      val = val.slice(0, -1)
    } else {
      val += ch
      process.stdout.write('*')
    }
  }
  process.stdin.resume()
  process.stdin.setEncoding('utf8')
  process.stdin.on('data', handler)
})

function step(n, total, msg) {
  console.log(`\n  [${n}/${total}] ${msg}`)
  console.log('  ' + '─'.repeat(50))
}

function ok(msg)   { console.log(`  ✅  ${msg}`) }
function err(msg)  { console.log(`  ❌  ${msg}`) }
function info(msg) { console.log(`  ℹ   ${msg}`) }

async function run() {
  console.clear()
  console.log('  ╔══════════════════════════════════════╗')
  console.log('  ║       Life Map v2 — Setup Wizard     ║')
  console.log('  ╚══════════════════════════════════════╝\n')
  console.log('  This wizard will get you running in ~5 minutes.')
  console.log('  You need: Supabase project, Google AI Studio key,')
  console.log('  and optionally a Discord bot.\n')
  await ask('  Press Enter to start...')

  const TOTAL = 7

  // ── Step 1: Node version ──────────────────────────────────────────────────
  step(1, TOTAL, 'Checking Node.js version')
  const nodeVer = process.version
  const major   = parseInt(nodeVer.slice(1))
  if (major < 20) {
    err(`Node.js ${nodeVer} detected. Version 20+ required.`)
    err('Install from: https://nodejs.org')
    process.exit(1)
  }
  ok(`Node.js ${nodeVer}`)

  // ── Step 2: Collect credentials ───────────────────────────────────────────
  step(2, TOTAL, 'API credentials')
  console.log('  Get these from:')
  console.log('  • Supabase → Settings → API')
  console.log('  • Google AI Studio → aistudio.google.com\n')

  const SUPABASE_URL         = (await ask('  Supabase project URL: ')).trim()
  const SUPABASE_SERVICE_KEY = (await askSecret('  Supabase service role key: ')).trim()
  const GOOGLE_API_KEY       = (await askSecret('  Google AI Studio key: ')).trim()

  // Generate a random CRON_SECRET
  const CRON_SECRET = Math.random().toString(36).slice(2) +
                      Math.random().toString(36).slice(2)

  if (!SUPABASE_URL.startsWith('https://') || !SUPABASE_SERVICE_KEY || !GOOGLE_API_KEY) {
    err('One or more required values are missing or look wrong.')
    process.exit(1)
  }
  ok('Credentials collected')

  // ── Step 3: Discord (optional) ────────────────────────────────────────────
  step(3, TOTAL, 'Discord setup (optional)')
  console.log('  Discord lets you add tasks and get briefings without opening the app.')
  const useDiscord = (await ask('  Set up Discord now? (y/n): ')).trim().toLowerCase()

  let DISCORD_BOT_TOKEN   = ''
  let DISCORD_WEBHOOK_URL = ''
  let DISCORD_CHANNEL_ID  = ''

  if (useDiscord === 'y') {
    console.log('\n  You need:')
    console.log('  • Discord bot token (discord.com/developers/applications)')
    console.log('  • Channel ID (right-click channel → Copy Channel ID)')
    console.log('  • Webhook URL (channel settings → Integrations → Webhooks)\n')
    DISCORD_BOT_TOKEN   = (await askSecret('  Bot token: ')).trim()
    DISCORD_CHANNEL_ID  = (await ask('  Channel ID: ')).trim()
    DISCORD_WEBHOOK_URL = (await ask('  Webhook URL: ')).trim()
    ok('Discord credentials collected')
  } else {
    info('Skipping Discord — you can add it later by editing api/.env')
  }

  // ── Step 4: Write .env ────────────────────────────────────────────────────
  step(4, TOTAL, 'Writing api/.env')

  const env = [
    `# Life Map v2 — generated by setup.js`,
    `SUPABASE_URL=${SUPABASE_URL}`,
    `SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}`,
    `GOOGLE_API_KEY=${GOOGLE_API_KEY}`,
    `CRON_SECRET=${CRON_SECRET}`,
    ``,
    `# Discord (leave blank if not using)`,
    `DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}`,
    `DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}`,
    `DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}`,
  ].join('\n')

  writeFileSync(ENV_PATH, env)
  ok(`api/.env written`)
  info(`CRON_SECRET generated: ${CRON_SECRET}`)
  info(`Save this — you'll need it as a GitHub secret (SERVER_URL + CRON_SECRET)`)

  // ── Step 5: npm install ───────────────────────────────────────────────────
  step(5, TOTAL, 'Installing dependencies')
  try {
    execSync('npm install', { cwd: API_DIR, stdio: 'inherit' })
    ok('Dependencies installed')
  } catch {
    err('npm install failed. Check the error above.')
    process.exit(1)
  }

  // ── Step 6: Database ──────────────────────────────────────────────────────
  step(6, TOTAL, 'Database setup')
  console.log('  Run these three files in your Supabase SQL editor, in order:')
  console.log()
  console.log('    1. supabase/schema.sql')
  console.log('    2. supabase/functions.sql')
  console.log('    3. supabase/seed.sql')
  console.log()
  console.log(`  Supabase SQL editor: ${SUPABASE_URL.replace('.supabase.co', '.supabase.co/project/default/sql/new')}`)
  console.log()
  await ask('  Press Enter once all three files have been run...')
  ok('Database setup confirmed')

  // ── Step 7: Embed seed + health check ────────────────────────────────────
  step(7, TOTAL, 'Seeding stat embeddings')
  console.log('  This calls the Gemini embedding API for each stat (~6 calls).\n')

  try {
    execSync('node ../scripts/embed-seed.js', { cwd: API_DIR, stdio: 'inherit' })
    ok('Stat embeddings seeded')
  } catch {
    err('Embedding seed failed. Check your GOOGLE_API_KEY.')
    info('You can re-run: node scripts/embed-seed.js')
  }

  // ── Done ──────────────────────────────────────────────────────────────────
  console.log()
  console.log('  ╔══════════════════════════════════════╗')
  console.log('  ║            Setup complete!           ║')
  console.log('  ╚══════════════════════════════════════╝\n')
  console.log('  Next steps:\n')
  console.log('  1. Start the server:')
  console.log('       cd api && node src/server.js\n')
  console.log('  2. Test it:')
  console.log('       curl http://localhost:3001/health')
  console.log('       curl http://localhost:3001/state\n')
  console.log('  3. Deploy to Render:')
  console.log('       • Push to GitHub')
  console.log('       • render.com → New → Blueprint → connect repo')
  console.log('       • Set env vars in Render dashboard\n')
  console.log('  4. Add GitHub secrets for cron jobs:')
  console.log(`       SERVER_URL = your Render URL`)
  console.log(`       CRON_SECRET = ${CRON_SECRET}\n`)

  if (useDiscord !== 'y') {
    console.log('  5. Add Discord later:')
    console.log('       Edit api/.env — add DISCORD_BOT_TOKEN, DISCORD_CHANNEL_ID, DISCORD_WEBHOOK_URL')
    console.log('       See README.md for Discord setup guide\n')
  }

  rl.close()
}

run().catch(err => {
  console.error('\n  Unexpected error:', err.message)
  process.exit(1)
})